	LIST	P=PIC16F84A
	INCLUDE	"P16F84A.INC"
	
	__CONFIG	_HS_OSC

TMP0	EQU	0CH
TMP1	EQU	0DH
	
	ORG	0H
MAIN
	BSF	STATUS, 	RP0	;Bank1
	CLRF	TRISB		;PortB->out
	MOVLW	01FH		;00011111->W
	MOVWF	TRISA		;PortA->input
	BCF	STATUS, 	RP0	;Bank0
	CLRF	PORTB		;ALL RB->low
LOOP
	MOVF	PORTA, 	W	;PortA->W
	ANDLW	B'00000001'		;RA0->W
	MOVWF	TMP0		;W->TMP0
	MOVF	PORTA, 	W	;PortA->W
	ANDLW	B'00000010'		;RA1->W
	MOVWF	TMP1		;W->TMP1
	BCF	STATUS, 	C	;C->low
	RRF	TMP1, 	W	;rotate right TMP1 with C ->W
	IORWF	TMP0, 	W	;RA0|RA1->W
	MOVWF	PORTB		;W->PortB
	GOTO	LOOP
	END