	LIST	P=PIC16F84A
	INCLUDE	"P16F84A.INC"
	
	__CONFIG	_HS_OSC
	
	ORG	0H
MAIN
	BSF	STATUS,	RP0	;Bank1
	CLRF	TRISB		;RB->output
	MOVLW	01FH		;00011111->W
	MOVWF	TRISA		;RA->input
	BCF	STATUS,	RP0	;Band 0
	CLRF	PORTB		;ALL RB->low
LOOP
	MOVF	PORTA,	W	;RA->W
	MOVWF	PORTB		;RA->RB
	GOTO	LOOP
	END